micronaut:
  application:
    name: devex
  ssl:
    enabled: true
  http:
    client:
      http-version: 2.0
      read-timeout: 60s

gitlab:
  url: "https://gitlab.com"

github:
  url: "https://api.github.com"

terraform:
  command: "terraform"
  secrets:
    - aws_iam_access_key
    - tls_private_key
